# HeadsPlus
# Plugin by Thatsmusic99
# Disclaimer: Any options added that are not followed by the config instructions will break the plugin. Patches are being introduced to stop this from happening, however please do not post a fake error because of it. Any config-related errors will require you to include your config.
# If all is clear, I will fix it.
# Otherwise, you will be ignored by me on Spigot.
# Thanks in advance, and thank you for using HeadsPlus. ~


blacklistOn: true
blacklist: []
version: 1

zombieHeadN: MHF_Zombie
zombieHeadC: 25
zombieHeadDN: 'Zombie Head'

skeletonHeadN: MHF_Skeleton
skeletonHeadC: 25
skeletonHeadDN: 'Skeleton Head'

blazeHeadN: MHF_Blaze
blazeHeadC: 10
blazeHeadDN: 'Blaze Head'

cavespiderHeadN: MHF_Cavespider
cavespiderHeadC: 25
cavespiderHeadDN: 'Cave Spider Head'

chickenHeadN: MHF_Chicken
chickenHeadC: 10
chickenHeadDN: 'Chicken Head'