# HeadsPlus
# Plugin by Thatsmusic99
# Disclaimer: sellHeads and craftHeads will not take immediate effect when /hp reload is used. Because they are event or command related, they cannot be undone once the server starts. I will include a fix for this soon however.
# Thanks in advance, and thank you for using HeadsPlus. ~
# players-lose-money-on-head-drop: true
# lost-money:
#  percentage: 0
#  amount: 0