# HeadsPlus
# Plugin by Thatsmusic99
# Disclaimer: sellHeads and craftHeads will not take immediate effect when /hp reload is used. Because they are event or command related, they cannot be undone once the server starts. I will include a fix for this soon however.
# Thanks in advance, and thank you for using HeadsPlus. ~

blacklistOn: true
blacklistwOn: true
whitelistOn: false
whitelistwOn: false
sellHeads: true
dropHeads: true
craftHeads: false
autoReloadOnFirstJoin: true
disableCrafting: false
headsDatabase: true
themeColor1: DARK_BLUE
themeColor2: GOLD
themeColor3: GRAY
themeColor4: DARK_AQUA
blacklistw: []
blacklist: []
whitelist: []
whitelistw: []
update-checker: true
update-notify: true
stop-placement-of-sellable-heads: false
mysql-host: localhost
mysql-port: 3306
mysql-database: db
mysql-username: username
mysql-password: password
mysql-usage: false
leaderboards: true
smite-player-if-they-get-a-head: false
theme: classic
pTheme: classic
gui-glass-color: SILVER
challenges: true
debug:
  create-debug-files: true
  print-stacktraces-in-console: true
use-lore: false
lore:
- '&6&lThis head can be sold!'
- '&6Do /sellhead to sell!'
player-death-messages: false
death-messages:
- "&b%p &3was killed by &b%k &3and had their head removed!"
- "&b%k &3finished the job and removed the worst part of &b%p&3: The head."
- "&3The server owner screamed at &b%p &3\"OFF WITH HIS HEAD!\"&3. &b%k &3finished the job."