################################################
#                                              #
#                 HEADSPLUS                    #
#                                              #
################################################

# Turn on the blacklist.
blacklistOn: true

# Blacklist list.
blacklist: []