main: io.github.thatsmusic99.headsplus.HeadsPlus
name: HeadsPlus
version: 3.1
description: Spawns in heads with extra features.
author: Thatsmusic99
commands:
    head:
        description: Spawns in a head.
        default: true
        permission: headsplus.head
    headsplus:
        description: Displays the help menu.
        default: true
        aliases: [hp]
        permission: headsplus.maincommand
    sellhead:
        description: Sells a head in a player's inventory.
        default: true    
        permission: headsplus.sellhead
    heads:
        description: Heads GUI command.
        default: true
        permission: headsplus.heads
